### ISSUE TITLE
500 is returned when accessing https://portal.vph-share.eu/filestore

### ISSUE THREAD

**Issue by dharezlak** [b3c/vphshare#149]

**Comment by asaglimbeni** [comment]
this is the error I recevied by the server ERROR: AttributeError: 'module' object has no attribute 'LOBCDER_FOLDER_DOWNLOAD_PATH'. 
I merge your last RFC request, maybe you need some new parameters in the settings.py ?

**Comment by dharezlak** [comment]
It looks like the following is also required: https://github.com/b3c/vphshare/commit/df935cc8ff02172723d325c8669dbaf0ea58005d

**Comment by asaglimbeni** [comment]
ok let me the time to merge it.

**Comment by asaglimbeni** [comment]
done let me know id it is ok.

**Comment by dharezlak** [comment]
Looks good now.
