### ISSUE TITLE
devel instance points to production Atmosphere

### ISSUE THREAD

**Issue by mkasztelnik** [b3c/vphshare#154]
I was trying to start new appliance on development env (devel.vph-share.eu), unfortunately it seems like clew is misconfigured and points to production Atmosphere instead of development one.

Please update link to Atmosphere into development one.

/cc @dharezlak, @tbartynski

**Comment by mkasztelnik** [comment]
@asaglimbeni any news about this issue?

**Comment by mkasztelnik** [comment]
@asaglimbeni please, please, please fix this issue. It is seriously hinder our development procedure.

**Comment by mkasztelnik** [comment]
[this line](https://github.com/b3c/vphshare/blob/master/masterinterface/settings.py#L297) should be changed into 

```python
CLOUDFACACE_URL = "https://vph-dev.cyfronet.pl/api/v1"
```

on development environment.

**Comment by asaglimbeni** [comment]
Hi Marek as far I saw, the local settings in the develop instance  already point to the develop cloudfacade.... So I don't know what is your issue...

**Comment by mkasztelnik** [comment]
@asaglimbeni please take a look at https://devel.vph-share.eu/applications/#switchToApplicationsView source. There you can find this element:

```html
<script type="text/javascript">
		var ClewOverrides = {
			cloudFacadeUrl: "https://vph.cyfronet.pl/api/v1",
			vphTicket: "xxx"
		}
    </script>
```

`cloudFacadeUrl` is used by cloud view to determine atmosphere url. The code responsible for this part is [here](https://github.com/b3c/vphshare/blob/master/masterinterface/cyfronet/templates/cyfronet/clew.html#L14). I'm not django expert but I believe `cloudFacadeUrl` is set [here](https://github.com/b3c/vphshare/blob/master/masterinterface/cyfronet/views.py#L83) so it is taken from the settings. Can you take a look once again at develop settings?

**Comment by asaglimbeni** [comment]
infact the reason was different, we changed some configuration on our apache server for some new features and the develop url pointed to the production istance :) I fixed it rigth now! Let me know if it is ok ofr you Thank you to report this :+1:   ( remeber the develop instance is the one with the rainbow header)

**Comment by mkasztelnik** [comment]
Now everything is :ok_hand:, thx for your help
