### ISSUE TITLE
Sentry token is exposed into public

### ISSUE THREAD

**Issue by mkasztelnik** [b3c/vphshare#155]
After looking into setting.py I found [this](https://github.com/b3c/vphshare/blob/master/masterinterface/settings.py#L359). It seems like sentry token is exposed into public.

**Comment by mkasztelnik** [comment]
Config file was updated, not it is this line https://github.com/b3c/vphshare/blob/master/masterinterface/settings.py#L367

**Comment by susheel** [comment]
@mkarmona - Close Issue
