### ISSUE TITLE
Cannot Download Files from Portal Filestore

### ISSUE THREAD

**Issue by susheel** [b3c/vphshare#157]
Platform: Mac OSX Yosemite (10.10.3)
Browser: Chrome Version 42.0.2311.90 (64-bit)

Steps to reproduce the problem:
1. Navigate to a file in Portal > Filestore
2. Click on download button

What is the expected result?
Expects the file to be downloaded

What happens instead?
Takes a long time and then times out

**Comment by dharezlak** [comment]
I ma also waiting a long time and then getting an Internal Server Error. I will let LOBCDER guys know.

**Comment by dharezlak** [comment]
LOBCDER team confirmed the problem. They are looking into it.

**Comment by asaglimbeni** [comment]
Yes, it is the same if you mount directly the webdav in your VM, It seems for some files is not able to download anymore, I have this issue since this Monday.

**Comment by susheel** [comment]
@mkarmona - Close Issue
