### ISSUE TITLE
None project is added for default project

### ISSUE THREAD

**Issue by mkasztelnik** [b3c/vphshare#161]
While embedding Atmosphere UI into https://portal.vph-share.eu/applications following Clew configuration is given:

```javascript 
var ClewOverrides = {
  cloudFacadeUrl: "https://vph.cyfronet.pl/api/v1",
  vphTicket: "xxx",
  project: "None"
}    
```

As a result Atmosphere is asking following `https://None.vph-share.eu` for resources available to the user. This is bad... Instead of none `nil` should be provided.

In the scope of this commit https://github.com/VPH-Share/atmosphere-vph/commit/17094c242de4778019fa8eac00b2da5e489c7311 I provided workaround for it. Please let me know when correct fix is deployed into production to remove this walkaround from atmosphere code.

**Comment by asaglimbeni** [comment]
The None it is the null value for python adn it happens only in the main vph-share portal. 
If you want I can fix it leaving empty the string , is it ok for you?
Alfredo

**Comment by mkasztelnik** [comment]
Empty string or valid json `null` are OK

**Comment by asaglimbeni** [comment]
Done https://github.com/b3c/vphshare/commit/2b573dc3a2dd59602e641558f736371f73116aef
